# Capture settings
CAPTURE_IMG_WIDTH = 128
CAPTURE_IMG_HEIGHT = 77
CAPTURE_N_FRAMES = 3
# OpenplanetBridgeSettings
OP_CHRONO_TO_WAIT_BEFORE_PLAYING = -200
# Env settings
ENV_MAX_FPS = 5
ENV_CP_REWARD = 1
ENV_FINISH_REWARD = 1
ENV_DEFAULT_REWARD = -0.0075
ENV_PLAYING_TIMEOUT = 30
# Draw settings
DRAW_LAYOUT_HEIGHT = 70
DRAW_LAYOUT_WIDTH = 100
DRAW_LAYOUT_TITLE_PADDING = 15
DRAW_LAYOUT_HEIGHT_DRAWER = DRAW_LAYOUT_HEIGHT - DRAW_LAYOUT_TITLE_PADDING
DRAW_LAYOUT_GRADUATION_PADDING = 10